### ISSUE TITLE
xocean:horn_skeleton is not a registered node!

### ISSUE THREAD

**Issue by daytonnvpaul** [starninjas/xocean#2]
This is causing a server crash when a player digs xocean:skelton_horn.

`ServerError:` AsyncErr: ServerThread::run Lua: Runtime error from mod 'xocean' in callback node_on_dig(): Runtime error from mod 'xocean' in callback node_after_des
truct(): "xocean:horn_skeleton" is not a registered node!`

Also, there appears to be a type in line [ https://github.com/starninjas/xocean/blob/master/init.lua#L807](url)

**Comment by Testyourstuff** [comment]
I just came across the same issue.

Looks like there's both xocean:horn_skeleton and xocean:skeleleton_horn used sometimes?

**Comment by daytonnvpaul** [comment]
I'm a little concerned the author hasn't responded in almost 2 weeks.  :(

**Comment by Testyourstuff** [comment]
As happens in manymany Minetest abandoned mods. Still, there's plenty of reasons the author may have to not see this issue. Maybe contact him on the forum?

Or maybe it's due to him developing on xocean 2.0?

See here: https://forum.minetest.net/viewtopic.php?f=9&t=22373&hilit=xocean&start=25

**Comment by TEbinger** [comment]
We also had a server crash due to that
2020-05-30 19:11:46: ACTION[Server]: 4starfighter2 digs xocean:skeleton_horn at (-640,-8,2455)
2020-05-30 19:11:46: ACTION[Main]: Server: Shutting down
2020-05-30 19:11:52: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'xocean' in callback node_on_dig(): Runtime error from mod 'xocean
' in callback node_after_destruct(): "xocean:horn_skeleton" is not a registered node!
2020-05-30 19:11:52: ERROR[Main]: stack traceback:
2020-05-30 19:11:52: ERROR[Main]:       [C]: in function 'set_node'
2020-05-30 19:11:52: ERROR[Main]:       ...est/minetest-5.2.0-dev-linux/bin/../mods/xocean/init.lua:839: in function <...est/minetest-5.2.0-dev-linux/bin/../mods/xocean/
init.lua:838>
2020-05-30 19:11:52: ERROR[Main]:       [C]: in function 'remove_node'
2020-05-30 19:11:52: ERROR[Main]:       ...st/minetest-5.2.0-dev-linux/bin/../builtin/game/item.lua:621: in function <...st/minetest-5.2.0-dev-linux/bin/../builtin/game/
item.lua:550>
2020-05-30 19:11:52: ERROR[Main]: stack traceback:
2020-05-30 19:11:52: ERROR[Main]:       [C]: in function 'remove_node'
2020-05-30 19:11:52: ERROR[Main]:       ...st/minetest-5.2.0-dev-linux/bin/../builtin/game/item.lua:621: in function <...st/minetest-5.2.0-dev-linux/bin/../builtin/game/
item.lua:550>

**Comment by daytonnvpaul** [comment]
Since the author of this mod still hasn't come up with a fix, I simply added an alias to my local overrides mod.

minetest.register_alias("xocean:horn_skeleton",  "xocean:skeleton_horn")

**Comment by starninjas** [comment]
It should be fixed now. Please test it out!

**Comment by axcore** [comment]
In the current version https://github.com/starninjas/xocean/commit/b39efae964026adbcf0c1836f0d579f184fecfc4 there are still three references to nodes that do not exist.

Line 782

`		minetest.set_node(pos, {name = "xocean:horn_block"})`

Should probably be `default:coral_brown`

Line 808 

`node_dig_prediction = "xocean:horn_skeleton",`

Line 846

`		minetest.set_node(pos, {name = "xocean:horn_skeleton"})`

Both should probably be `default:coral_skeleton`

**Comment by fluxionary** [comment]
@starninjas this is still an issue. i'm trying to figure out how to fix this, but i've found it hard to figure out what the intention is. if i submit a PR, it'll be w/ some heavily refactored code to break it into parts that i can understand.
